version: "3.8"

services:
  remix:
    container_name: remixrun
    build:
      context: . # Path to your Remix.run application directory
    ports:
      - "3000:3000" # Map host port to Remix.run container port
    depends_on:
      - mongodb
    environment:
      NODE_ENV: production # Set your desired NODE_ENV
      CENTRAL_DATABASE_URL: "mongodb://mongodb:27017/comclo_central"
      RAW_DATABASE_URL: "mongodb://mongodb:27017/"
      CLOUDINARY_NAME: "app-deity"
      CLOUDINARY_API_KEY: "452945375646228"
      CLOUDINARY_API_SECRET: "0d01yn4bWvTIJZeShhPyw2XXdZo"
      CENTRAL_DOMAIN: "localhost"
    command: ["npm", "run", "dev"] # Adjust your start command as needed

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017" # Map host port to MongoDB container port
    # environment:
    # MONGO_INITDB_DATABASE: comclo # Replace with your desired DB name
    # MONGO_INITDB_ROOT_USERNAME: kwamina
    # MONGO_INITDB_ROOT_PASSWORD: Famous10
